services:
  web:
    image: nginx:latest
    working_dir: /web
    restart: unless-stopped
    volumes:
      - ./:/web/
      - ./.conf/nginx.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.roadmap.rule=Host(`roadmap.prstart.hu`)"
      - "traefik.http.routers.roadmap.entrypoints=websecure"
      - "traefik.http.routers.roadmap.tls.certresolver=myresolver"
      - "traefik.http.routers.roadmap.service=roadmap"
      - "traefik.http.services.roadmap.loadbalancer.server.port=80"
    networks:
      - traefik

networks:
  traefik:
    external: true
